(function () {
  const state = { season: 'all', conference: 'all', team: 'all', playType: 'all', measure: 'win_pct' };
  const labels = { win_pct: 'Win percentage', wins: 'Wins', losses: 'Losses', point_diff: 'Point differential', plays: 'Plays', yards: 'Recorded yards', touchdowns: 'Touchdowns' };
  const format = (measure, value) => measure === 'win_pct' ? `${(Number(value) * 100).toFixed(1)}%` : Math.round(Number(value)).toLocaleString('en-US');
  const colors = ['#2769df', '#f47f69', '#8065c7', '#4baea2', '#d9a334'];

  function svgFrame(target, width = 720, height = 300) {
    target.innerHTML = `<svg viewBox="0 0 ${width} ${height}" preserveAspectRatio="xMinYMin meet" overflow="visible" role="img" aria-label="College football panel chart"></svg>`;
    return target.querySelector('svg');
  }
  function node(name, attrs, parent) { const item = document.createElementNS('http://www.w3.org/2000/svg', name); Object.entries(attrs).forEach(([key, value]) => item.setAttribute(key, value)); parent.appendChild(item); return item; }
  function text(svg, x, y, value, className = '', anchor = 'start') { node('text', { x, y, class: className, 'text-anchor': anchor }, svg).textContent = value; }
  function empty(target, message) { target.innerHTML = `<div class="chart-empty">${message}</div>`; }
  function bars(target, rows, valueKey, labelKey = 'label', valueFormat = (value) => Math.round(value).toLocaleString('en-US')) {
    if (!rows.length) return empty(target, 'No football rows match these filters.');
    const width = 720; const rowHeight = rows.length > 12 ? 27 : 42; const height = Math.max(250, rows.length * rowHeight + 58); const left = 180; const right = 105; const top = 28; const plot = width - left - right; const max = Math.max(...rows.map((row) => Number(row[valueKey]) || 0), 1); const svg = svgFrame(target, width, height);
    [0, .5, 1].forEach((fraction) => { const x = left + plot * fraction; node('line', { x1: x, y1: top - 12, x2: x, y2: height - 25, class: 'grid-line' }, svg); text(svg, x, 16, valueFormat(max * fraction), 'axis-label axis-number', 'middle'); });
    rows.forEach((row, index) => { const value = Number(row[valueKey]) || 0; const y = top + index * rowHeight; text(svg, left - 12, y + 17, row[labelKey], 'axis-label axis-left', 'end'); node('rect', { x: left, y: y + 3, width: plot * value / max, height: 20, rx: 3, class: 'bar', fill: colors[index % colors.length] }, svg); text(svg, Math.min(width - 8, left + plot * value / max + 8), y + 18, valueFormat(value), 'bar-label', left + plot * value / max > width - 104 ? 'end' : 'start'); });
  }
  function line(target, rows, valueKey, valueFormat = (value) => Math.round(value).toLocaleString('en-US')) {
    if (!rows.length) return empty(target, 'No football rows match these filters.');
    const width = 720; const height = 290; const left = 65; const right = 100; const top = 28; const bottom = 44; const plotWidth = width - left - right; const plotHeight = height - top - bottom; const max = Math.max(...rows.map((row) => Number(row[valueKey]) || 0), 1); const svg = svgFrame(target, width, height);
    [0, .5, 1].forEach((fraction) => { const y = top + plotHeight * (1 - fraction); node('line', { x1: left, y1: y, x2: width - right, y2: y, class: 'grid-line' }, svg); text(svg, left - 10, y + 4, valueFormat(max * fraction), 'axis-label axis-number', 'end'); });
    const points = rows.map((row, index) => ({ row, x: left + (rows.length === 1 ? plotWidth / 2 : plotWidth * index / (rows.length - 1)), y: top + plotHeight * (1 - (Number(row[valueKey]) || 0) / max) }));
    points.forEach((point, index) => { if (index) node('line', { x1: points[index - 1].x, y1: points[index - 1].y, x2: point.x, y2: point.y, class: 'chart-line', stroke: '#2769df' }, svg); node('circle', { cx: point.x, cy: point.y, r: 6, class: 'chart-point', fill: '#2769df' }, svg); text(svg, point.x, height - 15, point.row.label, 'axis-label axis-number', 'middle'); text(svg, point.x, point.y - 11, valueFormat(point.row[valueKey]), 'chart-value', 'middle'); });
  }
  function aggregate(rows, key, measure) {
    const groups = {};
    rows.forEach((row) => { const value = groups[row[key]] ||= { label: row[key], games: 0, wins: 0, losses: 0, ties: 0, point_diff: 0, plays: 0, yards: 0, touchdowns: 0 }; groups[row[key]].games += Number(row.games) || 0; groups[row[key]].wins += Number(row.wins) || 0; groups[row[key]].losses += Number(row.losses) || 0; groups[row[key]].ties += Number(row.ties) || 0; groups[row[key]].point_diff += Number(row.point_diff) || 0; groups[row[key]].plays += Number(row.plays) || 0; groups[row[key]].yards += Number(row.yards) || 0; groups[row[key]].touchdowns += Number(row.touchdowns) || 0; });
    return Object.values(groups).map((row) => ({ ...row, win_pct: row.games ? (row.wins + row.ties * .5) / row.games : 0 })).sort((a, b) => (Number(b[measure]) || 0) - (Number(a[measure]) || 0));
  }
  function filteredTeamRows(data) { return data.rows.filter((row) => (state.season === 'all' || String(row.season) === state.season) && (state.conference === 'all' || row.conference === state.conference) && (state.team === 'all' || row.team === state.team)); }
  function filteredPlayRows(data) { return data.rows.filter((row) => (state.season === 'all' || String(row.season) === state.season) && (state.conference === 'all' || row.conference === state.conference) && (state.team === 'all' || row.team === state.team) && (state.playType === 'all' || row.play_type === state.playType)); }
  function updateTeamOptions(rows) { const select = document.querySelector('#footballTeamFilter'); const current = state.team; const teams = [...new Set(rows.filter((row) => state.conference === 'all' || row.conference === state.conference).map((row) => row.team))].sort(); select.innerHTML = '<option value="all">All teams</option>' + teams.map((team) => `<option value="${team}">${team}</option>`).join(''); select.value = teams.includes(current) ? current : 'all'; state.team = select.value; }
  function updateKpis(rows, playRows) { const games = rows.reduce((sum, row) => sum + Number(row.games || 0), 0); const wins = rows.reduce((sum, row) => sum + Number(row.wins || 0), 0); const plays = rows.reduce((sum, row) => sum + Number(row.plays || 0), 0); const pct = games ? wins / games : 0; document.querySelector('#footballKpiOne').textContent = `${(pct * 100).toFixed(1)}%`; document.querySelector('#footballKpiTwo').textContent = games.toLocaleString('en-US'); document.querySelector('#footballKpiThree').textContent = plays.toLocaleString('en-US'); document.querySelector('#footballKpiFour').textContent = new Set(rows.map((row) => row.team)).size.toLocaleString('en-US'); document.querySelector('#footballPanelNote').textContent = `${playRows.reduce((sum, row) => sum + Number(row.plays || 0), 0).toLocaleString('en-US')} play-type rows represented in the current browser view.`; }
  function updateTable(rows) { const body = document.querySelector('#footballPanelTable'); body.innerHTML = rows.slice().sort((a, b) => b.win_pct - a.win_pct).slice(0, 80).map((row) => `<tr><td>${row.season}</td><td class="table-key">${row.team}</td><td>${row.conference}</td><td>${row.wins}–${row.losses}${row.ties ? `–${row.ties}` : ''}</td><td>${(row.win_pct * 100).toFixed(1)}%</td><td>${Math.round(row.point_diff).toLocaleString('en-US')}</td><td>${Math.round(row.plays).toLocaleString('en-US')}</td></tr>`).join(''); document.querySelector('#footballTableNote').textContent = `${Math.min(80, rows.length)} of ${rows.length} team-season rows shown`; }
  function render(data, playData) {
    updateTeamOptions(data.rows); const rows = filteredTeamRows(data); const playRows = filteredPlayRows(playData); const measure = state.measure; updateKpis(rows, playRows); updateTable(rows);
    const seasons = aggregate(rows, 'season', measure).sort((a, b) => a.label - b.label).map((row) => ({ ...row, label: String(row.label) })); const conferences = aggregate(rows, 'conference', measure).slice(0, 15); const teams = aggregate(rows, 'team', measure).slice(0, 12); const types = playRows.reduce((groups, row) => { const item = groups[row.play_type] ||= { label: row.play_type, plays: 0, yards: 0, touchdowns: 0 }; item.plays += Number(row.plays) || 0; item.yards += Number(row.yards) || 0; item.touchdowns += Number(row.touchdowns) || 0; return groups; }, {});
    line(document.querySelector('#footballSeasonChart'), seasons, measure, (value) => format(measure, value)); bars(document.querySelector('#footballConferenceChart'), conferences, measure, 'label', (value) => format(measure, value)); bars(document.querySelector('#footballTeamChart'), teams, measure, 'label', (value) => format(measure, value)); bars(document.querySelector('#footballPlayTypeChart'), Object.values(types).sort((a, b) => b.plays - a.plays), 'plays', 'label', (value) => Math.round(value).toLocaleString('en-US')); document.querySelector('#footballPanelMeasureLabel').textContent = labels[measure];
  }
  function bind(data, playData) {
    const controls = [['footballSeasonFilter', 'season'], ['footballConferenceFilter', 'conference'], ['footballTeamFilter', 'team'], ['footballPlayTypeFilter', 'playType'], ['footballMeasureFilter', 'measure']]; controls.forEach(([id, key]) => document.querySelector(`#${id}`).addEventListener('change', (event) => { state[key] = event.target.value; render(data, playData); })); document.querySelector('#footballReset').addEventListener('click', () => { Object.assign(state, { season: 'all', conference: 'all', team: 'all', playType: 'all', measure: 'win_pct' }); controls.forEach(([id, key]) => { if (document.querySelector(`#${id}`)) document.querySelector(`#${id}`).value = state[key]; }); render(data, playData); });
  }
  Promise.all([fetch('data/football_team_seasons.json').then((response) => response.json()), fetch('data/football_play_types.json').then((response) => response.json())]).then(([data, playData]) => { const seasons = [...new Set(data.rows.map((row) => row.season))].sort(); document.querySelector('#footballSeasonFilter').innerHTML = '<option value="all">All seasons</option>' + seasons.map((year) => `<option value="${year}">${year} season</option>`).join(''); const conferences = [...new Set(data.rows.map((row) => row.conference))].sort(); document.querySelector('#footballConferenceFilter').innerHTML = '<option value="all">All conferences</option>' + conferences.map((conference) => `<option value="${conference}">${conference}</option>`).join(''); const types = [...new Set(playData.rows.map((row) => row.play_type))].sort(); document.querySelector('#footballPlayTypeFilter').innerHTML = '<option value="all">All play types</option>' + types.map((type) => `<option value="${type}">${type}</option>`).join(''); updateTeamOptions(data.rows); bind(data, playData); render(data, playData); }).catch((error) => { document.querySelectorAll('.football-panel .chart-wrap').forEach((target) => empty(target, `Football panel could not load: ${error.message}`)); });
})();
